GET http://localhost:3000/api/test
###

POST http://localhost:3000/api/register
Content-Type: application/json

{
  "fullName": "second user",
  "email": "user1@example.com",
  "password": "securepassword"
}
###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "securepassword"
}
###

# /(!name || !description || !price || !category || !brand || !stock || !images)

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "New Product",
  "description": "This is a new product",
  "price": 99.99,
  "category": "Electronics",
  "brand": "Brand Name",
  "stock": 100,
  "isTrending": true,
  "images": ["image1.jpg", "image2.jpg"]
}
###

GET http://localhost:3000/api/products
###